;******************************************************************************
;                                                                             *
;     Filaname:     proyecto 1 -> Proyecto 1.asm                              *
;     Date         25 /08/2020                                                *
;     File version: v.2                                                       *
;     author :       Yefry Sajquiy - 18748                                    *
;     ompany;        UVG                                                      *
;     Description:   proyecto 1. Reloj                                        *
;                                                                             *
;******************************************************************************

; CONFIGURACION DEL PIC 16F887
    
#include "p16f887.inc"
; CONFIG1
; __config 0xE0F1
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
;------------------------- DECLARACION DE VARIABLES ---------------------------

    GPR_VAR UDATA
 
    AÑO		    RES 1
    ALARMA_ON_BAN   RES 1
   
    BANDERA_A	    RES 1
    BANDERA_B	    RES 1
    BANDERA_C	    RES 1
    BANDERA_D	    RES 1
    BANDERA_ES_1    RES 1
    BANDERA_ES_2    RES 1
    BANDERA_ES_3    RES 1
    BANDERA_FECHA   RES 1
 
	    
    CONT_1S	    RES 1
    CONT_60S	    RES 1
    CONT_500MS	    RES 1
    CONT1	    RES 1
    CONT2	    RES 1
    CONT_ALARMA    RES 1
	    
    DELAY_1	    RES 1
    DIA_UNI	    RES 1
    DIA_DEC	    RES 1
    DISPLAY_1	    RES 1
    DISPLAY_2	    RES 1
    DISPLAY_3	    RES 1
    DISPLAY_4	    RES 1
    DIA_U_MAX	    RES 1
    DIA_D_MAX	    RES 1
	    
    HORA_U	    RES 1
    HORA_D	    RES 1
    HORA24	    RES 1
    HORA_U_ALARM    RES 1
    HORA_D_ALARM    RES 1
	    
    INTER_LED	    RES 1 
	    
    MIN_U	    RES 1
    MIN_D	    RES 1
    MES		    RES 1
    MES_U	    RES 1
    MES_D	    RES 1
    MES12	    RES 1    
    MIN_U_ALARM	    RES 1
    MIN_D_ALARM	    RES 1
 
    STOP	    RES 1
    STOP_DIA	    RES 1
    STOP_MES	    RES 1
    STOP_ALARM	    RES 1
    STATUS_TEMP	    RES 1
	    
    W_TEMP	    RES 1
	    
;----------------------------------- MACRO -------------------------------------
	    
DEBOUNCE MACRO PORT, PIN    ;MACRO PARA ANTIREBOTE 
    CALL   DELAY_R1	
    BTFSC  PORT, PIN
    GOTO   $-1		 
ENDM

;-------------------------------------------------------------------------------

RES_VECT CODE 0x0000 
    GOTO SETUP 
    
;-------------------------------- INTERRUPCION ---------------------------------
    
ISR_VECT CODE 0x0004
 
PUSH:
    MOVWF   W_TEMP ;INICIO DE INTERRUPCION
    SWAPF   STATUS,W
    MOVWF   STATUS_TEMP
    
ISR:
    BTFSC   INTCON, T0IF ;0
    CALL    FUE_TIMER0 
    BTFSC   PIR1,TMR1IF 
    CALL    FUE_TIMER1 
    BTFSC   PIR1,TMR2IF 
    CALL    FUE_TIMER2 
    
POP:
    SWAPF   STATUS_TEMP,W
    MOVWF   STATUS
    SWAPF   W_TEMP,F   
    SWAPF   W_TEMP,W
    RETFIE

;------------------------- MAIN PROGRAM ----------------------------------------
    
MAIN_PROG CODE ; 
 
SETUP			;SE A LLAMA CADA CONFIGURACION PARA EL PIC
    CALL CONFIG_IO	    
    CALL CONFIG_TIMER0
    CALL CONFIG_TIMER1
    CALL CONFIG_TIMER2
    CALL CONFIG_INTERRUPCIONES
    
;------------------------------ LOOP -------------------------------------------
    
LOOP
    BTFSC   PORTA,RA3   ;BOTON PARA MOSTRAR FECHA, CUANDO SE MANTIENE PRESIONADO
    GOTO    FECHA_OFF
    GOTO    FECHA_ON
    
;----------------------- RUTINA BOTONES CON LOS ESTADOS ------------------------
    
; ESTADOS
; ESTADO 1 = HORA, SE PUEDE MODIFICAR LA HORA CON EL PRIMER PUSH
; ESTADO 2 = FECHA, SE PUEDE MODIFICAR LA FEHCA CON EL SEGUNDO PUSH
; ESTADO 3 = ALARMA, SE PUEDE MODIFICAR LA ALARMA CON EL TERCER PUSH
    
MODIFICAR_HORA:		;ENTRA AL ESTADO 1
    DEBOUNCE PORTA,RA0
    BSF BANDERA_ES_1,0	;INICIA LA BANDERA PARA APAGAR EL RELOJ DE TIEMPO 
    BSF PORTB,RB3	;ENCIENDE UN LED PARA MOSTRAR EL ESTADO DONDE SE ENCUENTRA
    
MODIFICAR_HORA_INIT:	
    MOVF    HORA_D,W	;CARGA LOS VALORES DE HORA EN LOS DISPLAY
    MOVWF   DISPLAY_1
    MOVF    HORA_U,W
    MOVWF   DISPLAY_2
    MOVF    MIN_D,W
    MOVWF   DISPLAY_3
    MOVF    MIN_U,W
    MOVWF   DISPLAY_4
    BTFSC   PORTA,RA1	    ;SE VERIFICA SI EL PUSH 2 SE ACTIVA PARA AUMENTAR LOS MINUTOS
    CALL    AUMENTAR_MIN_ES_1
    BTFSC   PORTA,RA0	    ;SE VERIFICA SI EL PUSH 1 SE ACTIVA PARA AUMENTAR LA HORA 
    CALL    AUMENTAR_HORA_ES_1
    BTFSS   PORTA,RA3	    ;SE VERIFICA SI EL PUSH 4 SE ACTIVA PARA SALIR DEL ESTADO 1
    GOTO    MODIFICAR_HORA_INIT
    DEBOUNCE PORTA,RA3
    BCF	    BANDERA_ES_1,0 
    BCF	    PORTB,RB3	    ;SE APAGA EL LED
    RETURN
    
AUMENTAR_MIN_ES_1:
    DEBOUNCE PORTA,RA1
    INCF    MIN_U	;AUMENTA MINUTOS EN UNA UNIDAD
    CALL    CONTMIN_U	;LLAMA A LA RUTINA CONTMIN PARA REINICIAR EL CONTEO DE MINUTOS
    RETURN 

AUMENTAR_HORA_ES_1:
    DEBOUNCE PORTA,RA0
    INCF    HORA_U	;INCREMENTA LA HORA EN UNA UNIDAD
    CALL    CONT_HORAS
    RETURN
    
MODIFICAR_FECHA:	;RUTINA PARA MODIFICAR FECHA ESATADO 2
    DEBOUNCE PORTA,RA1
    BSF BANDERA_ES_2,0 
    BSF PORTB,RB3	;ENCIENDE 2 LEDS
    BSF PORTB,RB1
    
MODIFICAR_FECHA_INIT:	; MODIFICA LA FECHA 
    MOVF    MES_D,W	;CARGA LOS VALORES DE MES A LOS DISPLAY
    MOVWF   DISPLAY_1
    MOVF    MES_U,W
    MOVWF   DISPLAY_2
    MOVF    DIA_DEC,W
    MOVWF   DISPLAY_3
    MOVF    DIA_UNI,W
    MOVWF   DISPLAY_4
    BTFSC   PORTA,RA1
    CALL    AUMENTAR_DIA_ES_2 ;SE VERIFICA SI EL PUSH 2 SE ACTIVA PARA AUMENTAR LOS DIAS
    BTFSC   PORTA,RA0
    CALL    AUMENTAR_MES_ES_2 ;SE VERIFICA SI EL PUSH 1 SE ACTIVA PARA AUMENTAR LOS MESES
    BTFSS   PORTA,RA3
    GOTO    MODIFICAR_FECHA_INIT ;SE VERIFICA SI EL PUSH 4 SE ACTIVA PARA SALIR DEL ESTADO 2
    DEBOUNCE PORTA,RA3
    BCF	    BANDERA_ES_2,0  ;APAGA LA BANDERA_ES_2
    BCF	    PORTB,RB3	    ;APAGA LOS LEDS
    BCF	    PORTB,RB1
RETURN
    
AUMENTAR_DIA_ES_2:
    DEBOUNCE PORTB,RB6
    INCF    DIA_UNI	;AUMENTA LOS DIAS EN UNA UNIDAD 
    CALL    CONT_DIAS	;LLAMA A LA RUTINA PARA RESETEAR LOS DIAS CUANDO HALLA CARRY
RETURN

AUMENTAR_MES_ES_2:
    DEBOUNCE PORTA,RA0
    INCF    MES_U	;AUMENTA EL MES EN UNA UNIDAD
    CALL    CONT_MESES	;LLAMA A LA RUTINA PARA RESETEAR EL MES
RETURN
    
    
;----------------------- MOSTRAR FECHA CON UN BOTON ----------------------------
 
FECHA_ON:   ;CONFIGURACION PARA MOSTSRAR LA FECHA
    BCF	    PORTB,RB1	;SE ENCIENDE LED PARA MOSTRAR ES ESTADO DE LA FECHA
    MOVF    HORA_D,W	
    MOVWF   DISPLAY_1
    MOVF    HORA_U,W
    MOVWF   DISPLAY_2
    MOVF    MIN_D,W
    MOVWF   DISPLAY_3
    MOVF    MIN_U,W
    MOVWF   DISPLAY_4
    CALL    DELAY_R1
    GOTO    FIN_BANDERA_FECHA
    
FECHA_OFF:  ;CONFIGURACION PARA MOSTRAR FECHA
    BSF	    PORTB,RB1	;APAGA LED PARA SALIR DEL ESTADO DE FECHA
    MOVF    MES_D,W	
    MOVWF   DISPLAY_1
    MOVF    MES_U,W
    MOVWF   DISPLAY_2
    MOVF    DIA_DEC,W
    MOVWF   DISPLAY_3
    MOVF    DIA_UNI,W
    MOVWF   DISPLAY_4
    CALL    DELAY_R1
    
FIN_BANDERA_FECHA:	; FIN D ELA BANDERA Y SE VERIFICA SI PRESIONA UN PUSH
    BTFSC   PORTA,RA0	    
    CALL    MODIFICAR_HORA
    BTFSC   PORTA,RA1	    
    CALL    MODIFICAR_FECHA
    BTFSC   PORTA,RA2
    CALL    MODIFICAR_ALARMA 
    GOTO    LOOP
    
;---------------------------CONFIGURACIONES-------------------------------------
CONFIG_IO:
    BANKSEL TRISA 
    CLRF    TRISA
    MOVLW   B'11111111'
    MOVWF   TRISA
    
    MOVLW   B'00000000'
    MOVWF    TRISC
    CLRF    PORTC
    
    MOVLW   B'00000000'
    MOVWF   TRISD
    CLRF    PORTD
    
    BANKSEL TRISB
    MOVLW   B'00000000'
    MOVWF   TRISB
    BANKSEL PORTB
    CLRF    PORTB
    
    
    BANKSEL ANSEL
    CLRF ANSEL
    CLRF ANSELH
    BANKSEL PORTA
    
 ;SE LIMPIAN LAS VARIABLES
    CLRF MIN_U
    CLRF MIN_D
    CLRF CONT_1S
    CLRF CONT_500MS
    CLRF INTER_LED
    CLRF BANDERA_A
    CLRF BANDERA_B
    CLRF BANDERA_C
    CLRF BANDERA_D
    CLRF HORA_U
    CLRF HORA_D
    CLRF DIA_UNI
    CLRF DIA_DEC
    CLRF MES_D
    CLRF MES_U
    CLRF MES
    CLRF ALARMA_ON_BAN
    CLRF MIN_U_ALARM
    CLRF MIN_D_ALARM
    CLRF HORA_D_ALARM
    CLRF HORA_U_ALARM
    CLRF CONT_ALARMA
    BSF	 BANDERA_A,0
    CLRF HORA24
    CLRF BANDERA_ES_1
    CLRF BANDERA_ES_2
    CLRF BANDERA_ES_3
    CLRF STOP_DIA
    CLRF STOP
    CLRF STOP_ALARM
    CLRF STOP_MES
 
;SE CONFIGURAN LOS VALORES INICIALES
    
    MOVLW .1 
    MOVWF DIA_UNI
    MOVWF MES_U
    MOVWF MES
    MOVLW .6
    MOVWF HORA_U_ALARM
    RETURN
 

CONFIG_TIMER0:
    BANKSEL OPTION_REG
    BCF	    OPTION_REG, T0CS ; SELECCIONAMOS TMR0 COMO TEMPORIZADOR
    BCF	    OPTION_REG, PSA ; ASIGNAMOS PRESCALER A TMR0
    BSF	    OPTION_REG, PS2
    BSF	    OPTION_REG, PS1 
    BSF	    OPTION_REG, PS0 ; PRESCALER DE 256
    BANKSEL PORTA	    ; CAMBIAMOS AL BANCO 0
    BCF	    INTCON, T0IF    ; APAGO LA BANDERA DE INTERRUPCION DEL TMR0
    MOVLW   .248    
    MOVWF   TMR0
    RETURN
    
CONFIG_TIMER1:
    BANKSEL T1CON
    BCF	    T1CON,TMR1ON
    BCF	    T1CON,T1CKPS1 ;PRESCALER DE 8
    BSF	    T1CON,T1CKPS0
    BCF	    T1CON,T1OSCEN
    BCF	    T1CON,TMR1CS
    BSF	    T1CON,TMR1ON
    MOVLW   03CH
    MOVWF   TMR1H
    MOVLW   0B0H
    MOVWF   TMR1L
    BCF	    PIR1,TMR1IF
    RETURN
    
CONFIG_TIMER2:
    BANKSEL T2CON
    MOVLW   B'01111111'
    MOVWF   T2CON
    BANKSEL PR2
    MOVLW   .39
    MOVWF   PR2
    BANKSEL PORTA
    CLRF    TMR2
    BCF	    PIR1,TMR2IF
    RETURN
    
CONFIG_INTERRUPCIONES:
   
    BANKSEL INTCON
    BCF	    INTCON, T0IF ; BORRAMOS BANDERA DE INTERRUPCIÓN
    BSF	    INTCON, T0IE ; HABILITO LA INTERRUPCIÓN DEL TMR0
    BSF	    INTCON, GIE ; HABILITO LAS INTERRUPCIONES GLOBALES
    BSF	    INTCON,PEIE
 
    BANKSEL PIE1
    BSF	    PIE1,TMR1IE
    BSF	    PIE1,TMR2IE
    BANKSEL PIR1
    BCF	    PIR1,TMR1IF
    BCF	    PIR1,TMR2IF
    RETURN
    
;------------------------------ TABLAS -----------------------------------------
    
TABLA_7SEG: ;TABLA PARA DECODIFICAR LOS VALORES DE LA TABLA, EN DISPLAY CATODO COMUN
    ANDLW   B'00001111';1
    ADDWF   PCL, F
    RETLW   B'00111111';0
    RETLW   B'00000110';1
    RETLW   B'01011011';2
    RETLW   B'01001111';3
    RETLW   B'01100110';4
    RETLW   B'01101101';5
    RETLW   B'01111101';6
    RETLW   B'00000111';7
    RETLW   B'01111111';8
    RETLW   B'01101111';9
    RETURN
    
TABLA_DIA_UNI_MAX: ;TABLA PARA LA MAXIMA UNIDAD DEL MES
    ADDWF PCL
    RETLW .2 ;0
    RETLW .2 ;ENERO
    RETLW .9 ;FEBRERO
    RETLW .2 ;MARZO
    RETLW .1 ;ABRIL
    RETLW .2 ;MAYO
    RETLW .1 ;JUNIO
    RETLW .2 ;JULIO
    RETLW .2 ;AGOSTO
    RETLW .1 ;SEPTIEMBRE
    RETLW .2 ;OCTUBRE
    RETLW .1 ;NOVIEMBRE
    RETLW .2 ;DICIEMBRE
    
TABLA_DIA_DEC_MAX: ;TABLA PARA EL VALOR DE LA DECENA
    ADDWF PCL
    RETLW .3 ;0
    RETLW .3 ;ENERO
    RETLW .2 ;FEBRERO
    RETLW .3 ;MARZO
    RETLW .3 ;ABRIL
    RETLW .3 ;MAYO
    RETLW .3 ;JUNIO
    RETLW .3 ;JULIO
    RETLW .3 ;AGOSTO
    RETLW .3 ;SEPTIEMBRE
    RETLW .3 ;OCTUBRE
    RETLW .3 ;NOVIEMBRE
    RETLW .3 ;DICIEMBRE

;------------ CONFIGURACION DE INTERRUPCIONES -----------------------------------

FUE_TIMER0:
    BCF	    INTCON, T0IF	; APAGO LA BANDERA DE INTERRUPCION DEL TMR0
    MOVLW   .240		;CARGA LOS VALORES A TMR0
    MOVWF   TMR0
    BTFSC   BANDERA_A,0	;	TESTEA LA BANDERA DEL DISPLAY 1
    GOTO    DISP_1		;VA AL DISPLAY 1
    BTFSC   BANDERA_B,0		;TESTEA LA BANDERA DEL DISPLAY 2
    GOTO    DISP_2		;VA AL DISPLAT 2
    BTFSC   BANDERA_C,0		;TESTEA LA BANDERA DEL DISPLAY 3
    GOTO    DISP_3		;VA AL DISPLAY 3
    BTFSC   BANDERA_D,0		;TESTEA LA BANDERA DEL DISPLAY 4
    GOTO    DISP_4		;VA AL DISPLAY 4
    RETURN
    
DISP_1:
    CLRF    PORTA
    BSF	    PORTD,RD1	;DISPLAY 1
    MOVF    DISPLAY_1,W
    CALL    TABLA_7SEG	;DECODIFICA EL VALOR DE DISPLAY 1
    MOVWF   PORTC	;MUESTRA EN DISPLAY
    BCF	    BANDERA_A,0 ;LIMPIA LA BANDERA A
    BSF	    BANDERA_B,0 ;ENCIENDE LA BANDERA B
    RETURN
    
DISP_2:
    CLRF    PORTD
    BSF	    PORTD,RD0	;DISPLAY 2
    MOVF    DISPLAY_2,W
    CALL    TABLA_7SEG	;DECODIFICA EL VALOR DE DISPLAY 2
    MOVWF   PORTC	;MUESTRA EN DISPLAY
    BCF	    BANDERA_B,0 ;LIMPIA LA BANDERA B
    BSF	    BANDERA_C,0 ;ENCIENDE LA BANDERA C
    RETURN
    
DISP_3:
    CLRF    PORTD
    BSF	    PORTD,RD3	;DISPLAY NO 3
    MOVF    DISPLAY_3,W
    CALL    TABLA_7SEG	;DECODIFICA EL VALOR DE DISPLAY 3
    MOVWF   PORTC	;MUESTRA EN DISPLAY
    BCF	    BANDERA_C,0 ;LIMPIA LA BANDERA C
    BSF	    BANDERA_D,0 ;ENCIENDE LA BANDERA D
    RETURN
    
DISP_4:
    CLRF    PORTD
    BSF	    PORTD,RD2	;DISPLAY NO 4
    MOVF    DISPLAY_4,W
    CALL    TABLA_7SEG ;DECODIFICA EL VALOR DE DISPLAY 4
    MOVWF   PORTC	;MUESTRA EN DISPLAY
    BSF	    BANDERA_A,0 ;ENCIENDE LA BANDERA A
    BCF	    BANDERA_D,0 ;LIMPIA LA BANDERA D
    RETURN
    
FUE_TIMER1:
    MOVLW   03CH
    MOVWF   TMR1H
    MOVLW   0B0H
    MOVWF   TMR1L
    BCF	    PIR1,TMR1IF
    BTFSC   BANDERA_ES_1,0 ;SALE SI ESTA LA BANDERA DE EST1 , EST2 , EST3
    RETURN
    BTFSC   BANDERA_ES_2,0
    RETURN
    BTFSC   BANDERA_ES_3,0
    RETURN
    CALL    CONT1SEGUNDO 
    CALL    CONTMIN_U 
    CALL    CONT_HORAS 
    CALL    CONT_DIAS 
    CALL    CONT_MESES ;
    
FINT1:
    RETURN
    
FUE_TIMER2:
    CLRF    TMR2	;RESETEA EL TMR2
    BCF	    PIR1,TMR2IF ;LIMPIA BANDERA DE TMR2
    INCF    CONT_500MS
    MOVF    CONT_500MS,W 
    SUBLW   .50
    BTFSS   STATUS,Z
    GOTO POP
    CLRF    CONT_500MS
    BTFSS   INTER_LED,0 
    GOTO    ON_LED
    GOTO    OFF_LED
    VERIFICAR_ALARMA_T2 
    BTFSC   BANDERA_ES_3,0
    RETURN
    GOTO    VER_HORA_D_ALARM 
    
FIN_TMR2
    RETURN

;------------------ CONFIGURACION DE RUTINAS PARA  LA ALARMA -------------------
    
VER_HORA_D_ALARM:	;VERIFICA SI LA HORA DE ALARMA ES IGUAL A LA HORA ACTUAL
    BCF	    STATUS,Z
    MOVF    HORA_D,W	;MUEVE EL VALOR DE HORA Al DISPLAY
    SUBWF   HORA_D_ALARM,W
    BTFSS   STATUS,Z
    GOTO    FIN_TMR2
    GOTO    VER_HORA_U_ALARM	;VERIFICA SI LA HORA DE ALARMA ES IGUAL A LA HORA ACTUAL
    
VER_HORA_U_ALARM:
    BCF	    STATUS,Z
    MOVF    HORA_U,W	;MUEVE EL VALOR DE HORA U A DISPLAY
    SUBWF   HORA_U_ALARM,W;
    BTFSS   STATUS,Z
    GOTO    FIN_TMR2
    GOTO    VER_MIN_D_ALARM
    
VER_MIN_D_ALARM:    ;VERIFICA SI LOS MINUTOS DE LA ALARMA ES IGUAL A LOS ACTUALES
    BCF	    STATUS,Z
    MOVF    MIN_D,W 
    SUBWF   MIN_D_ALARM,W
    BTFSS   STATUS,Z
    GOTO    FIN_TMR2
    GOTO    VER_MIN_U_ALARM

VER_MIN_U_ALARM:    ;VERIFICA SI LA MIN DE ALARMA ES IGUAL A LA MIN ACTUAL
    BCF	    STATUS,Z
    MOVF    MIN_U,W 
    SUBWF   MIN_U_ALARM,W
    BTFSS   STATUS,Z
    GOTO    FIN_TMR2
    BSF	    ALARMA_ON_BAN,0
    GOTO    FIN_TMR2
    
ON_LED:	    ;SI EL LED ESTA APAGADO LO ENCIENDE
    BSF	    INTER_LED,0
    BSF	    PORTB,RB0
    GOTO    VERIFICAR_ALARMA_T2
	    
OFF_LED:    ;SI EL LED ESTA ENCENDIDO LO APAGA
    BCF	    INTER_LED,0
    BCF	    PORTB,RB0
    GOTO    VERIFICAR_ALARMA_T2
    
ALARMA_ON:  ;SI TODOS LOS VALORES DE LA ALARMA SON IGUALES A LOS ACUALES INICIA
    BCF	    STATUS,Z 
    BSF	    PORTB,RB7
    INCF    CONT_ALARMA
    MOVF    CONT_ALARMA,W
    SUBLW   .60		    ;CUENTA A 60 PARA TERMINAR
    BTFSS   STATUS,Z 
    RETURN
    CLRF    CONT_ALARMA	    ;LIMPIA EL CONTADOR
    BCF	    PORTB,RB7	    ;SE APAGA LA ALARMA
    BCF	    ALARMA_ON_BAN,0
    RETURN
    
CONT1SEGUNDO: ;INICIA LA RUTINA DE INCREMENTAR SEGUNDOS
    BCF	    STATUS,Z
    INCF    CONT_1S	;INCREMENTA EL CONTADOR
    MOVF    CONT_1S,W
    SUBLW   .10		;CONFIGURACION DE 1 MINUTO 10*100MS = 1 S
    BTFSS   STATUS,Z 
    RETURN	
    CLRF    CONT_1S 
    INCF    MIN_U
    BTFSC   ALARMA_ON_BAN,0 ;TESTEA EL VALOR DE LA BANDERA DE ALARM
    CALL    ALARMA_ON
    RETURN
    
CONTMIN_U: ;CONTADOR DE 1 MINUTO
    BCF	    STATUS,Z
    MOVF    MIN_U,W
    SUBLW   .10
    BTFSS   STATUS,Z
    RETURN
    CLRF    MIN_U
    INCF    MIN_D
    BCF	    STATUS,Z
    MOVF    MIN_D,W
    SUBLW   .6
    BTFSS   STATUS,Z
    RETURN
    CLRF    MIN_D
    BTFSS   BANDERA_ES_1,0
    INCF    HORA_U 
    RETURN
    
CONT_HORAS: ;CONTADOR DE 10 MINUTOS
    BTFSC   STOP, 0
    CALL    PARAR
    BCF	    STATUS,Z
    MOVF    HORA_U,W
    SUBLW   .10  
    BTFSS   STATUS,Z
    RETURN
    CLRF    HORA_U
    INCF    HORA_D
    BCF	    STATUS,Z
    MOVF    HORA_D,W
    SUBLW   .2
    BTFSC   STATUS,Z
    BSF	    STOP,0
    RETURN
    
CONT_DIAS:  ;CONTADOR DE UN DIA
    BTFSC   STOP_DIA,0
    CALL    PARAR_DIA
    BCF	    STATUS,Z
    MOVF    DIA_UNI,W
    SUBLW   .10
    BTFSS   STATUS,Z
    RETURN
    CLRF    DIA_UNI
    INCF    DIA_DEC
    BCF	    STATUS,Z
    MOVF    MES,W
    CALL    TABLA_DIA_DEC_MAX
    SUBWF   DIA_DEC,W
    BTFSC   STATUS,Z
    BSF	    STOP_DIA,0
    RETURN
    
CONT_MESES: ;CONTADOR DE UN MES
    BTFSC   STOP_MES,0
    CALL    PARAR_MES
    BCF	    STATUS,Z
    MOVF    MES_U,W
    SUBLW   .10
    BTFSS   STATUS,Z
    RETURN
    CLRF    MES_U
    INCF    MES_D
    BSF	    STOP_MES,0
    RETURN
    
PARAR_DIA:  ;RUTINA PARA VERIFICAR EL ULTIMO DIA DEL MES
    MOVF    MES,W
    CALL    TABLA_DIA_UNI_MAX
    SUBWF   DIA_UNI,W
    BTFSC   STATUS, Z
    CALL    LIMPIAR_DIA ;LIMPIA TODOS LOS VALORES MENORES A UN DIA
    RETURN
    
PARAR:	    ;RUTINA PARA DETENER EL RELOJ DE 24 HORAS
    MOVF    HORA_U, W
    SUBLW   .4
    BTFSC   STATUS, Z
    CALL    LIMPIAR
    RETURN
    
PARAR_MES:  ;RUTINA PARA PARAR EL MES
    MOVF    MES_U,W
    SUBLW   .3
    BTFSC   STATUS,Z
    CALL    LIMPIAR_MES
    RETURN
    
LIMPIAR:    ;RUTINA PARA LIMPIAR DIA
    BTFSS   BANDERA_ES_1,0
    CLRF    MIN_U
    BTFSS   BANDERA_ES_1,0
    CLRF    MIN_D
    CLRF    HORA_U
    CLRF    HORA_D
    CLRF    STOP
    BTFSS   BANDERA_ES_1,0
    INCF    DIA_UNI, F
    RETURN
    
LIMPIAR_MES: ;LIMPIAR VALORES DEL MES
    MOVLW   .1
    MOVWF   MES_D
    CLRF    STOP_MES
    CLRF    DIA_DEC
    MOVLW   .1
    MOVWF   MES_U
    MOVWF   DIA_UNI
    MOVWF   MES
    INCF    AÑO
    RETURN
    
LIMPIAR_DIA: ;LIMPIA LOS VALORES DE DIA
    CLRF    DIA_DEC
    CLRF    STOP_DIA
    MOVLW   .1
    MOVWF   DIA_UNI
    BTFSS   BANDERA_ES_2,0
    INCF    MES_U
    BTFSS   BANDERA_ES_2,0
    INCF    MES
    RETURN

CONTMIN_U_ALARM:  
    BCF	    STATUS,Z
    MOVF    MIN_U_ALARM,W
    SUBLW   .10
    BTFSS   STATUS,Z
    RETURN
    CLRF    MIN_U_ALARM
    INCF    MIN_D_ALARM
    BCF	    STATUS,Z
    MOVF    MIN_D_ALARM,W
    SUBLW   .6
    BTFSS   STATUS,Z
    RETURN
    CLRF    MIN_D_ALARM ;AUMENTA LA HORA
    RETURN
    
CONT_HORAS_ALARM:
    BTFSC   STOP_ALARM, 0
    CALL    PARAR_ALARM
    BCF	    STATUS,Z
    MOVF    HORA_U_ALARM,W
    SUBLW   .10
    BTFSS   STATUS,Z
    RETURN
    CLRF    HORA_U_ALARM
    INCF    HORA_D_ALARM
    BCF	    STATUS,Z
    MOVF    HORA_D_ALARM,W
    SUBLW   .2
    BTFSC   STATUS,Z
    BSF	    STOP_ALARM,0
    RETURN
    
PARAR_ALARM:
    MOVF    HORA_U_ALARM, W
    SUBLW   .4
    BTFSC   STATUS, Z
    CALL    LIMPIAR_ALARM
    RETURN
    
LIMPIAR_ALARM:
    CLRF    MIN_U_ALARM
    CLRF    MIN_D_ALARM
    CLRF    HORA_U_ALARM
    CLRF    HORA_D_ALARM
    CLRF    STOP_ALARM
    RETURN
 
;--------------------------- --------------------------------------------------
MODIFICAR_ALARMA:	    ;MODIFICA LA ALARMA, ESTADO 3 
    DEBOUNCE PORTA,RA2
    BSF	    BANDERA_ES_3,0
    BSF	    PORTB,RB2	   ; SE ENCIENDE UN LED
    MODIFICAR_ALARMA_INIT
    MOVF    HORA_D_ALARM,W
    MOVWF   DISPLAY_1
    MOVF    HORA_U_ALARM,W
    MOVWF   DISPLAY_2
    MOVF    MIN_D_ALARM,W
    MOVWF   DISPLAY_3
    MOVF    MIN_U_ALARM,W
    MOVWF   DISPLAY_4
    BTFSC   PORTA,RA1	    ;SE VERIFICA SI EL PUSH 2 SE ACTIVA PARA AUMENTAR LOS DIAS
    CALL     AUMENTAR_MIN_ALARM_3 
    BTFSC   PORTA,RA0	    ;SE VERIFICA SI EL PUSH 1 SE ACTIVA PARA AUMENTAR LOS DIAS
    CALL    AUMENTAR_HORA_ALARM_3
    BTFSS   PORTA,RA3	    ;SE VERIFICA SI EL PUSH 4 SE ACTIVA PARA SALIR DEL ESTADO 3
    GOTO    MODIFICAR_ALARMA_INIT
    DEBOUNCE PORTA,RA3
    BCF	    BANDERA_ES_3,0
    BCF	    PORTB,RB2	    ; SE APAGA EL LED
    RETURN
    
AUMENTAR_MIN_ALARM_3:
    DEBOUNCE PORTA,RA1
    INCF    MIN_U_ALARM
    CALL    CONTMIN_U_ALARM
    RETURN
    
AUMENTAR_HORA_ALARM_3:
    DEBOUNCE PORTA,RA0
    INCF    HORA_U_ALARM
    CALL    CONT_HORAS_ALARM
    RETURN
    
;-------------------------- DELAY ----------------------------------------------
    
DELAY_R1:
    MOVLW   .250    
    MOVWF   DELAY_1
    DECFSZ  DELAY_1 
    GOTO    $-1	    
    RETURN

;-------------------- FIN DEL PROGRAMA -----------------------------------------
;-------------- XD     ---------------------------------------------------------
END